<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="LAPTOP-GCS6IJGA" name="Demo_TestNG.Demo_TestNG.TC_Login_DOM" tests="4" failures="0" timestamp="26 May 2020 07:39:45 GMT" time="0.012" errors="1">
  <testcase name="TC_Login_02" time="0.000" classname="Demo_TestNG.Demo_TestNG.TC_Login_DOM">
    <skipped/>
  </testcase> <!-- TC_Login_02 -->
  <testcase name="TC_Login_01" time="0.009" classname="Demo_TestNG.Demo_TestNG.TC_Login_DOM">
    <error type="java.lang.Exception" message="Intentionally">
      <![CDATA[java.lang.Exception: Intentionally
at Demo_TestNG.Demo_TestNG.TC_Login_DOM.TC_Login_01(TC_Login_DOM.java:11)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- TC_Login_01 -->
  <testcase name="TC_Login_04" time="0.001" classname="Demo_TestNG.Demo_TestNG.TC_Login_DOM"/>
  <testcase name="TC_Login_03" time="0.002" classname="Demo_TestNG.Demo_TestNG.TC_Login_DOM"/>
</testsuite> <!-- Demo_TestNG.Demo_TestNG.TC_Login_DOM -->
